name: DontPickUp
main: com.thefishnextdoor.dontpickup.Plugin
version: 0.0.1
api-version: 1.15
author: TheFishNextDoor
description: Description
commands:
  dontpickup:
    description: Description
    usage: /dontpickup <subcommand>
    aliases: [dpu]